### ISSUE TITLE
Custom Collection with svg files unter public folder?

### ISSUE THREAD

**Issue by awacode21** [nuxt/icon#239]
Our server bundle size is massive caused by nuxt icon. i guess it is because it includes all our svgs files as custom collections.
Is it possible to have custom collections with svg files that are located under the public folder so that they do not get part of the bundle size?
How would i need to configure this?
At the moment they cannot be loaded

**Comment by antfu** [comment]
I think the problem is more like, you have so many icons, but the icons as data needs to live in some form somewhere in your bundle. Client, server or static assets. It's obvious you don't want to always include all your icons in your client bundle, and let's see why Nuxt Icon does that in the server bundle; consider that the bundle size is less sensitive.

The problem with static assets is that not in all environments does the server have access to the filesystem. Nuxt Icon works by rendering with a small JSON data that represents your data, which means we need to parse your custom svg to get that data, in another word, we have to preprocess them at build time and serve as JS objects.

If you prefer to have icons as static assets (meaning we can't preprocess them), why don't you consider just embedding them as images instead?

**Comment by awacode21** [comment]
Your explanation makes so much sense to me! I dived deeper into the problem and i found one very problematic svg which made nearly 95% of the size of the whole thing. so i optimized it and now it is super cooler.
So my request / question is solved. I close the ticket. Thank you very much for your quick reply
